// 示例数据：覆盖占用、冻结、渐进片缺参、瞳距复核、修订版本链五种场景。

import { AppState, Prescription, WorkOrder } from "./types";

const T0 = 1_758_000_000_000;
const DAY = 86_400_000;

const rx: Prescription[] = [
  {
    id: "RX-1001",
    patientId: "Patient-032",
    eye: "OD",
    lensKind: "single",
    params: { sphere: -2.5, cylinder: -0.5, axis: 175, pd: 62, add: null, segHeight: null },
    status: "superseded",
    reviewRequired: false,
    rootId: "RX-1001",
    prevId: null,
    version: 1,
    orderId: "WO-2001",
    createdAt: T0 - 60 * DAY,
    updatedAt: T0 - 58 * DAY,
  },
  {
    id: "RX-1006",
    patientId: "Patient-032",
    eye: "OD",
    lensKind: "single",
    params: { sphere: -2.75, cylinder: -0.5, axis: 180, pd: 62, add: null, segHeight: null },
    status: "processed",
    reviewRequired: false,
    reviseReason: "半年复查近视进展 0.25D",
    rootId: "RX-1001",
    prevId: "RX-1001",
    version: 2,
    orderId: "WO-2004",
    createdAt: T0 - 20 * DAY,
    updatedAt: T0 - 18 * DAY,
  },
  {
    id: "RX-1002",
    patientId: "Patient-081",
    eye: "OS",
    lensKind: "progressive",
    // 渐进片初配：ADD 与瞳高尚未补，加工单排队中
    params: { sphere: 0.75, cylinder: 0, axis: null, pd: 64, add: null, segHeight: null },
    status: "frozen",
    reviewRequired: false,
    rootId: "RX-1002",
    prevId: null,
    version: 1,
    orderId: "WO-2002",
    createdAt: T0 - 2 * DAY,
    updatedAt: T0 - 2 * DAY,
  },
  {
    id: "RX-1003",
    patientId: "Patient-144",
    eye: "OS",
    lensKind: "single",
    params: { sphere: -1.5, cylinder: -1.0, axis: 15, pd: 58, add: null, segHeight: null },
    status: "pending",
    reviewRequired: false,
    rootId: "RX-1003",
    prevId: null,
    version: 1,
    orderId: null,
    createdAt: T0 - 1 * DAY,
    updatedAt: T0 - 1 * DAY,
  },
  {
    id: "RX-1004",
    patientId: "Patient-032",
    eye: "OS",
    lensKind: "single",
    // 瞳距 48mm 超出 50~80，必须待复核
    params: { sphere: -2.5, cylinder: 0, axis: null, pd: 48, add: null, segHeight: null },
    status: "pending",
    reviewRequired: true,
    rootId: "RX-1004",
    prevId: null,
    version: 1,
    orderId: null,
    createdAt: T0 - 3 * 3600_000,
    updatedAt: T0 - 3 * 3600_000,
  },
  {
    id: "RX-1005",
    patientId: "Patient-205",
    eye: "OD",
    lensKind: "progressive",
    params: { sphere: 1.0, cylinder: -0.75, axis: 90, pd: 66, add: 1.5, segHeight: 22 },
    status: "frozen",
    reviewRequired: false,
    rootId: "RX-1005",
    prevId: null,
    version: 1,
    orderId: "WO-2003",
    createdAt: T0 - 5 * 3600_000,
    updatedAt: T0 - 5 * 3600_000,
  },
];

const orders: WorkOrder[] = [
  {
    id: "WO-2001",
    prescriptionId: "RX-1001",
    patientId: "Patient-032",
    eye: "OD",
    lensKind: "single",
    frozenParams: { sphere: -2.5, cylinder: -0.5, axis: 175, pd: 62, add: null, segHeight: null },
    status: "done",
    checkNote: "轴位 175° 核验合格",
    createdAt: T0 - 58 * DAY,
    startedAt: T0 - 57 * DAY,
    finishedAt: T0 - 55 * DAY,
  },
  {
    id: "WO-2004",
    prescriptionId: "RX-1006",
    patientId: "Patient-032",
    eye: "OD",
    lensKind: "single",
    frozenParams: { sphere: -2.75, cylinder: -0.5, axis: 180, pd: 62, add: null, segHeight: null },
    status: "done",
    checkNote: "修订片核验合格",
    createdAt: T0 - 18 * DAY,
    startedAt: T0 - 17 * DAY,
    finishedAt: T0 - 15 * DAY,
  },
  {
    id: "WO-2002",
    prescriptionId: "RX-1002",
    patientId: "Patient-081",
    eye: "OS",
    lensKind: "progressive",
    frozenParams: { sphere: 0.75, cylinder: 0, axis: null, pd: 64, add: null, segHeight: null },
    status: "queued",
    checkNote: "",
    createdAt: T0 - 2 * DAY,
    startedAt: null,
    finishedAt: null,
  },
  {
    id: "WO-2003",
    prescriptionId: "RX-1005",
    patientId: "Patient-205",
    eye: "OD",
    lensKind: "progressive",
    frozenParams: { sphere: 1.0, cylinder: -0.75, axis: 90, pd: 66, add: 1.5, segHeight: 22 },
    status: "in_progress",
    checkNote: "",
    createdAt: T0 - 5 * 3600_000,
    startedAt: T0 - 2 * 3600_000,
    finishedAt: null,
  },
];

export const seedState: AppState = { prescriptions: rx, orders };
