import type { AppState, Prescription, ProcessingJob } from "./types";

// 示例数据：覆盖待加工、待复核（瞳距超限）、加工中（冻结快照）、
// 已加工 + 修订版本链、渐进片缺瞳高阻断开工等场景。

const rx = (p: Prescription): Prescription => p;

export const seedState: AppState = {
  prescriptions: [
    rx({
      id: "rx-003",
      rootId: "root-032-OD",
      version: 1,
      patientId: "Patient-032",
      patientName: "林小童",
      eye: "OD",
      sphere: -2.5,
      cylinder: -0.5,
      axis: 180,
      pd: 60,
      lensKind: "single",
      add: null,
      ph: null,
      status: "superseded",
      note: "初配单光片",
      createdAt: "2026-08-12T09:10:00.000Z",
      jobId: "job-001",
      revisionReason: null,
      supersedesId: null,
    }),
    rx({
      id: "rx-004",
      rootId: "root-032-OD",
      version: 2,
      patientId: "Patient-032",
      patientName: "林小童",
      eye: "OD",
      sphere: -2.75,
      cylinder: -0.5,
      axis: 180,
      pd: 61,
      lensKind: "single",
      add: null,
      ph: null,
      status: "processed",
      note: "近视进展 0.25D",
      createdAt: "2026-09-01T10:20:00.000Z",
      jobId: "job-002",
      revisionReason: "复查近视进展 0.25D，换片",
      supersedesId: "rx-003",
    }),
    rx({
      id: "rx-001",
      rootId: "root-081-OS",
      version: 1,
      patientId: "Patient-081",
      patientName: "王渐进",
      eye: "OS",
      sphere: +1.25,
      cylinder: 0,
      axis: null,
      pd: 64,
      lensKind: "progressive",
      add: 1.5,
      ph: null,
      status: "pending",
      note: "老视初配，瞳高待确认",
      createdAt: "2026-09-18T14:02:00.000Z",
      jobId: null,
      revisionReason: null,
      supersedesId: null,
    }),
    rx({
      id: "rx-002",
      rootId: "root-144-OD",
      version: 1,
      patientId: "Patient-144",
      patientName: "赵散光",
      eye: "OD",
      sphere: -1.0,
      cylinder: -1.25,
      axis: 90,
      pd: 84,
      lensKind: "single",
      add: null,
      ph: null,
      status: "review",
      note: "瞳距录入 84mm，疑多测一位",
      createdAt: "2026-09-19T11:40:00.000Z",
      jobId: null,
      revisionReason: null,
      supersedesId: null,
    }),
    rx({
      id: "rx-005",
      rootId: "root-205-OS",
      version: 1,
      patientId: "Patient-205",
      patientName: "陈清晰",
      eye: "OS",
      sphere: -3.5,
      cylinder: -0.75,
      axis: 15,
      pd: 58,
      lensKind: "single",
      add: null,
      ph: null,
      status: "processing",
      note: "",
      createdAt: "2026-09-20T08:30:00.000Z",
      jobId: "job-003",
      revisionReason: null,
      supersedesId: null,
    }),
  ],
  jobs: [
    {
      id: "job-001",
      patientId: "Patient-032",
      patientName: "林小童",
      eye: "OD",
      snapshot: {
        id: "rx-003",
        rootId: "root-032-OD",
        version: 1,
        patientId: "Patient-032",
        patientName: "林小童",
        eye: "OD",
        sphere: -2.5,
        cylinder: -0.5,
        axis: 180,
        pd: 60,
        lensKind: "single",
        add: null,
        ph: null,
        status: "processing",
        note: "初配单光片",
        createdAt: "2026-08-12T09:10:00.000Z",
        jobId: "job-001",
        revisionReason: null,
        supersedesId: null,
      },
      status: "done",
      createdAt: "2026-08-12T09:15:00.000Z",
      finishedAt: "2026-08-13T16:00:00.000Z",
    },
    {
      id: "job-002",
      patientId: "Patient-032",
      patientName: "林小童",
      eye: "OD",
      snapshot: {
        id: "rx-004",
        rootId: "root-032-OD",
        version: 2,
        patientId: "Patient-032",
        patientName: "林小童",
        eye: "OD",
        sphere: -2.75,
        cylinder: -0.5,
        axis: 180,
        pd: 61,
        lensKind: "single",
        add: null,
        ph: null,
        status: "processing",
        note: "近视进展 0.25D",
        createdAt: "2026-09-01T10:20:00.000Z",
        jobId: "job-002",
        revisionReason: "复查近视进展 0.25D，换片",
        supersedesId: "rx-003",
      },
      status: "done",
      createdAt: "2026-09-01T10:25:00.000Z",
      finishedAt: "2026-09-02T15:30:00.000Z",
    },
    {
      id: "job-003",
      patientId: "Patient-205",
      patientName: "陈清晰",
      eye: "OS",
      snapshot: {
        id: "rx-005",
        rootId: "root-205-OS",
        version: 1,
        patientId: "Patient-205",
        patientName: "陈清晰",
        eye: "OS",
        sphere: -3.5,
        cylinder: -0.75,
        axis: 15,
        pd: 58,
        lensKind: "single",
        add: null,
        ph: null,
        status: "processing",
        note: "",
        createdAt: "2026-09-20T08:30:00.000Z",
        jobId: "job-003",
        revisionReason: null,
        supersedesId: null,
      },
      status: "queued",
      createdAt: "2026-09-20T08:35:00.000Z",
      finishedAt: null,
    },
  ],
};
